retry:
  max-attempts: 10
  max-delay: 2000

integrations:
    fast-bank:
      applications-url: https://shop.uat.klix.app:443/api/FastBank/applications
    solid-bank:
      applications-url: https://shop.uat.klix.app:443/api/SolidBank/applications